version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"   # PostgreSQL accessible depuis l’hôte
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api      # Chemin vers le Dockerfile
    ports:
      - "8000:8000"   # API FastAPI disponible sur localhost:8000
    depends_on:
      - db            # L'API démarre après la base de données

volumes:
  db_data:
